[package]
name = "phenixrizen-zen-types"
description = "Zen Core Types (maintained fork of gorules/zen)"
version = "2.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/phenixrizen/zen.git"
homepage = "https://github.com/phenixrizen/zen"

[lib]
name = "zen_types"

[dependencies]
ahash = { workspace = true }
serde = { workspace = true, features = ["rc", "derive"] }
serde_json = { workspace = true, features = [] }
smallvec = { version = "1", features = ["union"] }
hipstr = { version = "0.8", features = ["serde"] }
rust_decimal = { workspace = true, features = ["maths-nopanic"] }
rust_decimal_macros = { workspace = true }
thiserror = { workspace = true }
nohash-hasher = { workspace = true }

[features]
default = []
arbitrary_precision = ["serde_json/arbitrary_precision"]
