[package]
authors = ["Phenix Rizen <phenixrizen@gmail.com>", "GoRules Team <bot@gorules.io>"]
description = "Zen Template Language (maintained fork of gorules/zen)"
name = "phenixrizen-zen-tmpl"
license = "MIT"
version = "2.2.0"
edition = "2021"
repository = "https://github.com/phenixrizen/zen.git"
homepage = "https://github.com/phenixrizen/zen"

[lib]
name = "zen_tmpl"

[dependencies]
zen-expression = { package = "phenixrizen-zen-expression", path = "../expression", version = "2.0.1" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["regex-deprecated"]

regex-lite = ["zen-expression/regex-lite"]
regex-deprecated = ["zen-expression/regex-deprecated"]
arbitrary_precision = ["zen-expression/arbitrary_precision"]