[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "phenixrizen-zen-engine"
dynamic = ["version"]   # taken from Cargo.toml by maturin
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

description = "Open-Source Business Rules Engine (maintained fork of gorules/zen)"
readme = "README.md"
authors = [{ name = "Phenix Rizen", email = "phenixrizen@gmail.com" }]
license = { file = "LICENSE" }

keywords = ["gorules",
    "zen-engine",
    "business rules engine",
    "rules engine",
    "rule engine",
    "bre",
    "rule",
    "rules",
    "engine",
    "decision",
    "decision table",
    "rust",
    "pyo3"
]

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest", "asyncio"]

[project.urls]
Homepage = "https://gorules.io"
Documentation = "https://docs.gorules.io/developers/sdks/python"
Repository = "https://github.com/phenixrizen/zen"

[project.scripts]
zenengine = "reader.__main__:main"

[tool.maturin]
features = ["pyo3/extension-module", "sqlite"]
