[package]
name = "phenixrizen-zen-macros"
description = "Zen Helper Macros (maintained fork of gorules/zen)"
version = "2.0.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/phenixrizen/zen.git"
homepage = "https://github.com/phenixrizen/zen"

[lib]
name = "zen_macros"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
serde_derive_internals = "0.29"
